
package miniTwitter;

import javax.swing.*;


public class UserView extends javax.swing.JFrame {
    private String userInput;
    private final DefaultListModel<String> followingListModel;
    private final DefaultListModel<String> newsFeedListModel;
    private final String username;
    
    /**
     * Creates new form UserView
     * @param username
     */
    public UserView(String username) {
        initComponents();
        this.username = username;
        UserIdLabel.setText(username + " view");
        
        // following list
        followingListModel = new DefaultListModel<>();
        followingListModel.addElement("- Bob");
        followingListModel.addElement("- Steve");
        FollowingList.setModel(followingListModel);
        
        // twitter news feed
        newsFeedListModel = new DefaultListModel<>();
        newsFeedListModel.addElement("- Steve: Bob is awesome");
        newsFeedListModel.addElement("- Bob: I like to code");
        NewsFeed.setModel(newsFeedListModel);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        FollowButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FollowingList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TweetMessage = new javax.swing.JTextArea();
        Post = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NewsFeed = new javax.swing.JList<>();
        UserIdLabel = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FollowButton.setText("Follow");
        FollowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowButtonActionPerformed(evt);
            }
        });

        FollowingList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "- Bob", "- Steve" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(FollowingList);

        jLabel2.setText("Current Following");

        TweetMessage.setColumns(20);
        TweetMessage.setRows(5);
        TweetMessage.setText("Tweet Message");
        jScrollPane2.setViewportView(TweetMessage);

        Post.setText("Post Tweet");
        Post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostActionPerformed(evt);
            }
        });

        jLabel3.setText("News Feed");

        NewsFeed.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "- Steve: Bob is awesome", "- Bob: I like to code" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(NewsFeed);

        UserIdLabel.setText("User Id");

        Username.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Post, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(FollowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username)
                    .addComponent(FollowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(UserIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Post, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>                        

    private void FollowButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        userInput = Username.getText();
        System.out.println(userInput);
        followingListModel.addElement("- " + userInput);
    }                                            

    private void PostActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String tweet = TweetMessage.getText();
        newsFeedListModel.addElement("- " + username + ": " + tweet);
        TweetMessage.setText("");
        
        boolean isPos = tweet.contains("like") || tweet.contains("awesome") || tweet.contains("amazing");
        if(isPos == true){
            counters.addPositive();
        }
        counters.addTweet();
    }                                    


    // Variables declaration - do not modify                     
    private javax.swing.JButton FollowButton;
    private javax.swing.JList<String> FollowingList;
    private javax.swing.JList<String> NewsFeed;
    private javax.swing.JButton Post;
    private javax.swing.JTextArea TweetMessage;
    private javax.swing.JLabel UserIdLabel;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration                   

}
